[package]
name = "switch-toggle"
version = {workspace = true}
edition = "2021"
publish = false

[dependencies]
fastedge = { path = "../../" }
serde = "1.0"
serde_json = "1.0"
url = "2.5"

[lib]
crate-type = ["cdylib"]

